pref('extensions.fireserv.enabled', true);
pref('extensions.fireserv.debug', false);
pref('extensions.fireserv.htdocs', 'ProfD:/fireserv/htdocs');
pref('extensions.fireserv.log', 'ProfD:/fireserv/log');
pref('extensions.fireserv.data', 'ProfD:/fireserv/data');
pref('extensions.fireserv.port', 8080);
pref('extensions.fireserv.address', 'localhost');
pref('extensions.fireserv.parsers', 'sjs');
pref('extensions.fireserv.controllers', 'jsonrpc');
pref('extensions.fireserv.mimetypes', 'sjs|text/html; charset=utf-8');
pref('extensions.fireserv.directoryIndex', 'index.html');
pref('extensions.fireserv.autoIndex', true);
pref('extensions.fireserv.sessions', false);
pref('extensions.fireserv.sessions.autoSave', false);
pref('extensions.fireserv.expires', 30);
